sudo: required
services:
  - docker

before_install:
  - docker build -t oliverswanson/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true oliverswanson/docker-react-test npm run test

