sudo: required
services:
  - docker

before_install:
  - docker build -t oliverswanson/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true oliverswanson/docker-react-test npm run test

deploy:
  provider: elasticbeanstalk
  region: eu-north-1
  app: docker-react-test2
  env: "DockerReactTest2-env"
  bucket_name: "elasticbeanstalk-eu-north-1-355643322607"
  bucket_path: "docker-react-test2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

